<a href="https://colab.research.google.com/github/iseve001/CSC221_iseve001/blob/main/assignment26_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#cell 1
a = 45
b = 73.74238
c = 'teststring'

print(type(a), a, a + 7)
print(type(b), b, b*5)
print(type(c), c, c*5)

<class 'int'> 13 20
<class 'float'> 21.55674 107.78370000000001
<class 'str'> teststring teststringteststringteststringteststringteststring

In [ ]:
#cell 2
print(f'The variable is {a} and c*4 is {c*4}')

The variable is 13 and c*4 is teststringteststringteststringteststring

In [ ]:
#cell 3
name = 'ned lecky'
print(name, name.title())
upper = name.upper()
print(upper)

ned lecky Ned Lecky
NED LECKY

In [ ]:
#cell 4
abc = [13,26,52,7]
print(abc)
for x in sorted(abc):
  print(x)
print
print('abc min: ' + str(min(abc)))
print('abc max: ' + str(max(abc)))
print('abc sum: ' + str(sum(abc)))

[13, 26, 52, 7]
7
13
26
52
abc min: 7
abc min: 7
abc max: 52
abc sum: 98

In [ ]:
#cell 5
xyz = []
xyz.append([13,31,5])
xyz.append([12, 'asd'])
print(xyz)
xyz2 = ([31,12,5],[8,5],[12,'asd'])
print(xyz2)

[[13, 31, 5], [12, 'asd']]
([31, 12, 5], [8, 5], [12, 'asd'])

In [ ]:
#cell 6
abc = [8,4,2,1]
print(sorted(abc))
print(abc)

[1, 2, 4, 8]
[8, 4, 2, 1]

In [ ]:
#cell 7
def f1():
  for x in range(5,100,2):
    print(x, end = ' ')
f1()

5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

In [ ]:
#cell 8
print([x*x for x in range(1,1100) if x % 9 !=0])

[1, 4, 9, 16, 25, 36, 49, 64, 100, 121, 144, 169, 196, 225, 256, 289, 361, 400, 441, 484, 529, 576, 625, 676, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26569, 26896, 27225, 27556, 27889, 28224, 28561, 28900, 29584, 29929, 30276, 30625, 30976, 31329, 31684, 32041, 32761, 33124, 33489, 33856, 34225, 34596, 34969, 35344, 36100, 36481, 36864, 37249, 37636, 38025, 38416, 38809, 39601, 40000, 40401, 40804, 41209, 41616, 42025, 42436, 43264, 43681, 44100, 44521, 44944, 45369, 45796, 46225, 47089, 47524, 47961, 48400, 48841, 49284, 49729, 50176, 51076, 51529, 51984, 52441, 52900, 53361, 53824, 54289, 55225, 55696, 56169, 56644, 57121, 57600, 58081, 58564, 59536, 60025, 60516, 61009, 61504, 62001, 62500, 63001, 64009, 64516, 65025, 65536, 66049, 66564, 67081, 67600, 68644, 69169, 69696, 70225, 70756, 71289, 71824, 72361, 73441, 73984, 74529, 75076, 75625, 76176, 76729, 77284, 78400, 78961, 79524, 80089, 80656, 81225, 81796, 82369, 83521, 84100, 84681, 85264, 85849, 86436, 87025, 87616, 88804, 89401, 90000, 90601, 91204, 91809, 92416, 93025, 94249, 94864, 95481, 96100, 96721, 97344, 97969, 98596, 99856, 100489, 101124, 101761, 102400, 103041, 103684, 104329, 105625, 106276, 106929, 107584, 108241, 108900, 109561, 110224, 111556, 112225, 112896, 113569, 114244, 114921, 115600, 116281, 117649, 118336, 119025, 119716, 120409, 121104, 121801, 122500, 123904, 124609, 125316, 126025, 126736, 127449, 128164, 128881, 130321, 131044, 131769, 132496, 133225, 133956, 134689, 135424, 136900, 137641, 138384, 139129, 139876, 140625, 141376, 142129, 143641, 144400, 145161, 145924, 146689, 147456, 148225, 148996, 150544, 151321, 152100, 152881, 153664, 154449, 155236, 156025, 157609, 158404, 159201, 160000, 160801, 161604, 162409, 163216, 164836, 165649, 166464, 167281, 168100, 168921, 169744, 170569, 172225, 173056, 173889, 174724, 175561, 176400, 177241, 178084, 179776, 180625, 181476, 182329, 183184, 184041, 184900, 185761, 187489, 188356, 189225, 190096, 190969, 191844, 192721, 193600, 195364, 196249, 197136, 198025, 198916, 199809, 200704, 201601, 203401, 204304, 205209, 206116, 207025, 207936, 208849, 209764, 211600, 212521, 213444, 214369, 215296, 216225, 217156, 218089, 219961, 220900, 221841, 222784, 223729, 224676, 225625, 226576, 228484, 229441, 230400, 231361, 232324, 233289, 234256, 235225, 237169, 238144, 239121, 240100, 241081, 242064, 243049, 244036, 246016, 247009, 248004, 249001, 250000, 251001, 252004, 253009, 255025, 256036, 257049, 258064, 259081, 260100, 261121, 262144, 264196, 265225, 266256, 267289, 268324, 269361, 270400, 271441, 273529, 274576, 275625, 276676, 277729, 278784, 279841, 280900, 283024, 284089, 285156, 286225, 287296, 288369, 289444, 290521, 292681, 293764, 294849, 295936, 297025, 298116, 299209, 300304, 302500, 303601, 304704, 305809, 306916, 308025, 309136, 310249, 312481, 313600, 314721, 315844, 316969, 318096, 319225, 320356, 322624, 323761, 324900, 326041, 327184, 328329, 329476, 330625, 332929, 334084, 335241, 336400, 337561, 338724, 339889, 341056, 343396, 344569, 345744, 346921, 348100, 349281, 350464, 351649, 354025, 355216, 356409, 357604, 358801, 360000, 361201, 362404, 364816, 366025, 367236, 368449, 369664, 370881, 372100, 373321, 375769, 376996, 378225, 379456, 380689, 381924, 383161, 384400, 386884, 388129, 389376, 390625, 391876, 393129, 394384, 395641, 398161, 399424, 400689, 401956, 403225, 404496, 405769, 407044, 409600, 410881, 412164, 413449, 414736, 416025, 417316, 418609, 421201, 422500, 423801, 425104, 426409, 427716, 429025, 430336, 432964, 434281, 435600, 436921, 438244, 439569, 440896, 442225, 444889, 446224, 447561, 448900, 450241, 451584, 452929, 454276, 456976, 458329, 459684, 461041, 462400, 463761, 465124, 466489, 469225, 470596, 471969, 473344, 474721, 476100, 477481, 478864, 481636, 483025, 484416, 485809, 487204, 488601, 490000, 491401, 494209, 495616, 497025, 498436, 499849, 501264, 502681, 504100, 506944, 508369, 509796, 511225, 512656, 514089, 515524, 516961, 519841, 521284, 522729, 524176, 525625, 527076, 528529, 529984, 532900, 534361, 535824, 537289, 538756, 540225, 541696, 543169, 546121, 547600, 549081, 550564, 552049, 553536, 555025, 556516, 559504, 561001, 562500, 564001, 565504, 567009, 568516, 570025, 573049, 574564, 576081, 577600, 579121, 580644, 582169, 583696, 586756, 588289, 589824, 591361, 592900, 594441, 595984, 597529, 600625, 602176, 603729, 605284, 606841, 608400, 609961, 611524, 614656, 616225, 617796, 619369, 620944, 622521, 624100, 625681, 628849, 630436, 632025, 633616, 635209, 636804, 638401, 640000, 643204, 644809, 646416, 648025, 649636, 651249, 652864, 654481, 657721, 659344, 660969, 662596, 664225, 665856, 667489, 669124, 672400, 674041, 675684, 677329, 678976, 680625, 682276, 683929, 687241, 688900, 690561, 692224, 693889, 695556, 697225, 698896, 702244, 703921, 705600, 707281, 708964, 710649, 712336, 714025, 717409, 719104, 720801, 722500, 724201, 725904, 727609, 729316, 732736, 734449, 736164, 737881, 739600, 741321, 743044, 744769, 748225, 749956, 751689, 753424, 755161, 756900, 758641, 760384, 763876, 765625, 767376, 769129, 770884, 772641, 774400, 776161, 779689, 781456, 783225, 784996, 786769, 788544, 790321, 792100, 795664, 797449, 799236, 801025, 802816, 804609, 806404, 808201, 811801, 813604, 815409, 817216, 819025, 820836, 822649, 824464, 828100, 829921, 831744, 833569, 835396, 837225, 839056, 840889, 844561, 846400, 848241, 850084, 851929, 853776, 855625, 857476, 861184, 863041, 864900, 866761, 868624, 870489, 872356, 874225, 877969, 879844, 881721, 883600, 885481, 887364, 889249, 891136, 894916, 896809, 898704, 900601, 902500, 904401, 906304, 908209, 912025, 913936, 915849, 917764, 919681, 921600, 923521, 925444, 929296, 931225, 933156, 935089, 937024, 938961, 940900, 942841, 946729, 948676, 950625, 952576, 954529, 956484, 958441, 960400, 964324, 966289, 968256, 970225, 972196, 974169, 976144, 978121, 982081, 984064, 986049, 988036, 990025, 992016, 994009, 996004, 1000000, 1002001, 1004004, 1006009, 1008016, 1010025, 1012036, 1014049, 1018081, 1020100, 1022121, 1024144, 1026169, 1028196, 1030225, 1032256, 1036324, 1038361, 1040400, 1042441, 1044484, 1046529, 1048576, 1050625, 1054729, 1056784, 1058841, 1060900, 1062961, 1065024, 1067089, 1069156, 1073296, 1075369, 1077444, 1079521, 1081600, 1083681, 1085764, 1087849, 1092025, 1094116, 1096209, 1098304, 1100401, 1102500, 1104601, 1106704, 1110916, 1113025, 1115136, 1117249, 1119364, 1121481, 1123600, 1125721, 1129969, 1132096, 1134225, 1136356, 1138489, 1140624, 1142761, 1144900, 1149184, 1151329, 1153476, 1155625, 1157776, 1159929, 1162084, 1164241, 1168561, 1170724, 1172889, 1175056, 1177225, 1179396, 1181569, 1183744, 1188100, 1190281, 1192464, 1194649, 1196836, 1199025, 1201216, 1203409, 1207801]

In [2]:
#cell 9
def sieve_of_eratosthenes(limit):
    is_prime = [True] * (limit + 1)

    is_prime[0] = is_prime[1] = False
    for i in range(2, int(limit**0.5) + 1):
        if is_prime[i]:
            for j in range(i*i, limit + 1, i):
                is_prime[j] = False

    primes = [num for num in range(2, limit + 1) if is_prime[num]]
    return primes

limit = 5000
result = sieve_of_eratosthenes(limit)
print(result)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151, 1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223, 1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291, 1297, 1301, 1303, 1307, 1319, 1321, 1327, 1361, 1367, 1373, 1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439, 1447, 1451, 1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511, 1523, 1531, 1543, 1549, 1553, 1559, 1567, 1571, 1579, 1583, 1597, 1601, 1607, 1609, 1613, 1619, 1621, 1627, 1637, 1657, 1663, 1667, 1669, 1693, 1697, 1699, 1709, 1721, 1723, 1733, 1741, 1747, 1753, 1759, 1777, 1783, 1787, 1789, 1801, 1811, 1823, 1831, 1847, 1861, 1867, 1871, 1873, 1877, 1879, 1889, 1901, 1907, 1913, 1931, 1933, 1949, 1951, 1973, 1979, 1987, 1993, 1997, 1999, 2003, 2011, 2017, 2027, 2029, 2039, 2053, 2063, 2069, 2081, 2083, 2087, 2089, 2099, 2111, 2113, 2129, 2131, 2137, 2141, 2143, 2153, 2161, 2179, 2203, 2207, 2213, 2221, 2237, 2239, 2243, 2251, 2267, 2269, 2273, 2281, 2287, 2293, 2297, 2309, 2311, 2333, 2339, 2341, 2347, 2351, 2357, 2371, 2377, 2381, 2383, 2389, 2393, 2399, 2411, 2417, 2423, 2437, 2441, 2447, 2459, 2467, 2473, 2477, 2503, 2521, 2531, 2539, 2543, 2549, 2551, 2557, 2579, 2591, 2593, 2609, 2617, 2621, 2633, 2647, 2657, 2659, 2663, 2671, 2677, 2683, 2687, 2689, 2693, 2699, 2707, 2711, 2713, 2719, 2729, 2731, 2741, 2749, 2753, 2767, 2777, 2789, 2791, 2797, 2801, 2803, 2819, 2833, 2837, 2843, 2851, 2857, 2861, 2879, 2887, 2897, 2903, 2909, 2917, 2927, 2939, 2953, 2957, 2963, 2969, 2971, 2999, 3001, 3011, 3019, 3023, 3037, 3041, 3049, 3061, 3067, 3079, 3083, 3089, 3109, 3119, 3121, 3137, 3163, 3167, 3169, 3181, 3187, 3191, 3203, 3209, 3217, 3221, 3229, 3251, 3253, 3257, 3259, 3271, 3299, 3301, 3307, 3313, 3319, 3323, 3329, 3331, 3343, 3347, 3359, 3361, 3371, 3373, 3389, 3391, 3407, 3413, 3433, 3449, 3457, 3461, 3463, 3467, 3469, 3491, 3499, 3511, 3517, 3527, 3529, 3533, 3539, 3541, 3547, 3557, 3559, 3571, 3581, 3583, 3593, 3607, 3613, 3617, 3623, 3631, 3637, 3643, 3659, 3671, 3673, 3677, 3691, 3697, 3701, 3709, 3719, 3727, 3733, 3739, 3761, 3767, 3769, 3779, 3793, 3797, 3803, 3821, 3823, 3833, 3847, 3851, 3853, 3863, 3877, 3881, 3889, 3907, 3911, 3917, 3919, 3923, 3929, 3931, 3943, 3947, 3967, 3989, 4001, 4003, 4007, 4013, 4019, 4021, 4027, 4049, 4051, 4057, 4073, 4079, 4091, 4093, 4099, 4111, 4127, 4129, 4133, 4139, 4153, 4157, 4159, 4177, 4201, 4211, 4217, 4219, 4229, 4231, 4241, 4243, 4253, 4259, 4261, 4271, 4273, 4283, 4289, 4297, 4327, 4337, 4339, 4349, 4357, 4363, 4373, 4391, 4397, 4409, 4421, 4423, 4441, 4447, 4451, 4457, 4463, 4481, 4483, 4493, 4507, 4513, 4517, 4519, 4523, 4547, 4549, 4561, 4567, 4583, 4591, 4597, 4603, 4621, 4637, 4639, 4643, 4649, 4651, 4657, 4663, 4673, 4679, 4691, 4703, 4721, 4723, 4729, 4733, 4751, 4759, 4783, 4787, 4789, 4793, 4799, 4801, 4813, 4817, 4831, 4861, 4871, 4877, 4889, 4903, 4909, 4919, 4931, 4933, 4937, 4943, 4951, 4957, 4967, 4969, 4973, 4987, 4993, 4999]

In [4]:
#10
def my_prime_generator(N):
    primes = sieve_of_eratosthenes(N)

    for x in primes:
        yield x

for x in my_prime_generator(200):
    print(x, end=' ')

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199

In [26]:
#cell 11
import random
gen = [random.randint(1, 1000) for i in range(1000)]
min = min(gen)
max = max(gen)
sum = sum(gen)
avg = sum / len(gen)
print(avg)

TypeError: ignored

In [59]:
#cell 12
import random
num = random.randint(1,3)
if (1<num<3):
  print("Your number is 2")
elif(num == 1):
  print("your number might be 2")
else:
  print("Your number is not 2")

your number might be 2

In [ ]:
#cell 13
#the fact that it was created over 2 decades ago
#the way it's completely optional
#there's many ways to do it

In [62]:
#cell 14
%%file testfile.txt
Alex, Dog
Jack, Cat
Fluff, Lizard
Marshmellow, Hamster

Overwriting testfile.txt

In [66]:
#cell 15
dict1 = {}
with open('testfile.txt') as file:
    while line := file.readline():
        line = line.strip()
        key, value = line.split(',')
        dict1[key] = value.strip()
print(dict1)

{'Alex': 'Dog', 'Jack': 'Cat', 'Fluff': 'Lizard', 'Marshmellow': 'Hamster'}

In [67]:
#16
print(dict1.values())
pet_types = set(dict1.values())
print(pet_types)

dict_values(['Dog', 'Cat', 'Lizard', 'Hamster'])
{'Dog', 'Cat', 'Hamster', 'Lizard'}

In [81]:
#17
n = 80
while n >= 16:
    print(n)
    n -= 8
#18
#def f1(n1, n2, n3):
#  max_n = max(n1, n2, n3)
#  min_n = min(n1, n2, n3)
#  sum_n = sum([n1, n2, n3])
#  return min_n, max_n, sum_n
#print(f1(13, 21, 4))

#19
def f2(*n):
    max_n = max(n)
    min_n = min(n)
    sum_n = sum(n)

    return min_n, max_n, sum_n

print(f2(13, 21, 4, 81, -5, 30, 12))

80
72
64
56
48
40
32
24
16

TypeError: ignored

In [82]:
#20
def traceroo(func):
  def newfunc(*args, **kwargs):
    print(f'(func.__name__) {args} {kwargs}')
    return func(*args, **kwargs)
f1d = traceroo(f1)
print(f1(3, 2,1))
print(f1d(3,2,1))
@traceroo
def f4():
  print("Hi I'm f4")
f4()

TypeError: ignored

In [85]:
#pytest
%%file functions.py
def f5(a):
    ret = a+5
    print(ret)
    return ret
def f6(a, b):
    return a+b

Overwriting functions.py

In [86]:
%%file test_functions.py
import functions as ff

def test_test1():
    assert ff.f5(5) == 5+5
    assert ff.f6(5, 7) == 12

def test_test2():
    assert ff.f5(8) == 8+5
    assert ff.f6(5, 9) == 13

Writing test_functions.py